import ThemeRegistry from "@/utils/ThemeRegistry";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Container } from "@mui/material";
import Box from "@mui/material/Box";
import Stack from "@mui/material/Stack";

import StandardLayout from "@/components/StandardLayout";
import NavBar from "@/components/NavBar/NavBar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Ally Global",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Box
          sx={{
            maxWidth: `100%`,
            overflowX: `hidden`,
            // pt: "72px",
          }}
        >
          <ThemeRegistry options={{ key: "mui-theme" }}>
            <NavBar />
            <Container
              maxWidth="xl"
              sx={{
                paddingLeft: "0px !important",
                paddingRight: "0px !important",
              }}
            >
              <Stack
                sx={{
                  mb: 4,
                }}
                spacing={{
                  xs: 10,
                  md: 20,
                }}
                direction={"column"}
              >
                {children}
              </Stack>
              {/* <Footer /> */}
            </Container>
          </ThemeRegistry>
        </Box>
      </body>
    </html>
  );
}
