import ThemeRegistry from "@/utils/ThemeRegistry";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Container } from "@mui/material";
import Box from "@mui/material/Box";
import Stack from "@mui/material/Stack";
import { Analytics } from "@vercel/analytics/react";

import StandardLayout from "@/components/StandardLayout";
import NavBar from "@/components/NavBar/NavBar";
import Footer from "@/sections/Footer";
import { LogBreakpointWrapper } from "@/hooks/useLogBreakpoints";
import GoogleAnalytics from "@/components/GoogleAnalytics";

const inter = Inter({ subsets: ["latin"] });

const title = "The Prevention Project";
const image = {
  url: "/images/seo-image.jpg",
  width: 1100,
  height: 1200,
};

export const metadata: Metadata = {
  title,
  // description: "Generated by create next app",
  openGraph: {
    title,
    images: [
      {
        url: image.url,
        width: image.width,
        height: image.height,
      },
    ],
  },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <GoogleAnalytics />
      <body className={inter.className}>
        <Analytics />
        <Box
          sx={{
            maxWidth: `100%`,
            overflowX: `hidden`,
            pt: "72px",
          }}
        >
          <ThemeRegistry options={{ key: "mui-theme" }}>
            <LogBreakpointWrapper>
              <NavBar />
              <Container
                maxWidth="xl"
                sx={{
                  paddingLeft: "0px !important",
                  paddingRight: "0px !important",
                }}
              >
                <Stack
                  sx={{
                    mb: 4,
                  }}
                  direction={"column"}
                >
                  {children}
                </Stack>
                <StandardLayout>
                  <Footer />
                </StandardLayout>
              </Container>
            </LogBreakpointWrapper>
          </ThemeRegistry>
        </Box>
      </body>
    </html>
  );
}
