import ThemeRegistry from "@/utils/ThemeRegistry";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Container } from "@mui/material";
import Box from "@mui/material/Box";
import Stack from "@mui/material/Stack";

import StandardLayout from "@/components/StandardLayout";
import Footer from "@/sections/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "The Prevention Project",
  // description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Box
          sx={{
            maxWidth: `100%`,
            overflowX: `hidden`,
          }}
        >
          <ThemeRegistry options={{ key: "mui-theme" }}>
            <Container
              maxWidth="xl"
              sx={{
                paddingLeft: "0px !important",
                paddingRight: "0px !important",
              }}
            >
              {children}
            </Container>
          </ThemeRegistry>
        </Box>
      </body>
    </html>
  );
}
